CC=gcc
CFLAGS=-I.

bit_manipulation: bit_manipulation.c
	@echo "Building bit_manipulation"
	$(CC) -o bit_manipulation bit_manipulation.c

clean: clean_bit_manipulation
	@echo "Cleaning all"

clean_bit_manipulation:
	@echo "Cleaning bit_manipulation"
	rm bit_manipulation
